#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, re, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RECORD_DIR = ROOT / 'scripts/applications/records'
BEGIN = '# BEGIN AI-SANDBOX APP {name}'
END = '# END AI-SANDBOX APP {name}'

class HelperError(RuntimeError): pass

def text(path: str) -> str:
    return (ROOT / path).read_text(encoding='utf-8')

def write(path: str, data: str):
    (ROOT / path).write_text(data, encoding='utf-8')

def insert_before(path: str, anchor: str, block: str, name: str, last: bool=False):
    p=ROOT/path; s=p.read_text(encoding='utf-8')
    # A single application legitimately has multiple marked blocks in Dockerfile
    # and run-with-ssm-secrets. Duplicate onboarding is prevented by the record file.
    idx=s.rfind(anchor) if last else s.find(anchor)
    if idx < 0: raise HelperError(f'{path}: insertion anchor not found: {anchor}')
    p.write_text(s[:idx]+block.rstrip()+'\n'+s[idx:], encoding='utf-8')

def remove_marked(path: Path, name: str) -> int:
    s=path.read_text(encoding='utf-8')
    pat=re.compile(r'(?ms)^'+re.escape(BEGIN.format(name=name))+r'\r?\n.*?^'+re.escape(END.format(name=name))+r'\r?\n?')
    ns,n=pat.subn('',s)
    if n: path.write_text(ns,encoding='utf-8')
    return n

def validate_name(v: str):
    if not re.fullmatch(r'[a-z][a-z0-9-]{1,39}',v): raise HelperError('name must be lowercase a-z/0-9/hyphen, 2-40 chars')

def validate_cmd(v: str):
    if not re.fullmatch(r'[A-Za-z0-9._+-]+',v): raise HelperError('invalid command name')

def validate_domain(v: str):
    if not re.fullmatch(r'\.?[A-Za-z0-9][A-Za-z0-9.-]*[A-Za-z0-9]',v): raise HelperError(f'invalid egress domain: {v}')

def q(s: str) -> str:
    return "'"+s.replace("'", "'\\''")+"'"

def install_block(a) -> str:
    b=[BEGIN.format(name=a.name),'# Admin-approved install generated by v1.16.16 helper. Review before release.']
    if a.install_type=='npm':
        if not a.package or not a.version: raise HelperError('npm requires --package and exact --version')
        b += [f'RUN npm install --global --omit=dev --no-audit --no-fund {q(a.package+"@"+a.version)} \\', f'    && command -v {q(a.command)} >/dev/null']
    elif a.install_type=='uv':
        if not a.package or not a.version: raise HelperError('uv requires --package and exact --version')
        b += [f'RUN uv tool install --python /usr/bin/python3 {q(a.package+"=="+a.version)} \\', f'    && command -v {q(a.command)} >/dev/null']
    elif a.install_type=='apt':
        if not a.package or not a.version: raise HelperError('apt requires --package and exact --version')
        b += ['RUN apt-get update \\',f'    && apt-get install -y --no-install-recommends {q(a.package+"="+a.version)} \\','    && rm -rf /var/lib/apt/lists/* \\',f'    && command -v {q(a.command)} >/dev/null']
    elif a.install_type=='archive':
        if not a.url or not a.url.startswith('https://'): raise HelperError('archive requires HTTPS --url')
        if not a.sha256 or not re.fullmatch(r'[0-9a-fA-F]{64}',a.sha256): raise HelperError('archive requires 64-hex --sha256')
        if a.archive_format not in ('binary','zip','tar.gz'): raise HelperError('archive requires --archive-format binary|zip|tar.gz')
        tmp=f'/tmp/{a.name}-download'; ext=f'/tmp/{a.name}-extract'
        b += [f'RUN curl -fsSL --proto \'=https\' --tlsv1.2 {q(a.url)} -o {q(tmp)} \\', f"    && printf '%s  %s\\n' {q(a.sha256)} {q(tmp)} | sha256sum --check --strict - \\"]
        if a.archive_format=='binary':
            b += [f'    && install -m 0755 {q(tmp)} {q("/usr/local/bin/"+a.command)} \\',f'    && rm -f {q(tmp)}']
        else:
            if not a.binary_path or a.binary_path.startswith('/') or '..' in Path(a.binary_path).parts: raise HelperError('zip/tar.gz requires safe relative --binary-path')
            if a.archive_format=='zip': b += [f'    && mkdir -p {q(ext)} && unzip -q {q(tmp)} -d {q(ext)} \\']
            else: b += [f'    && mkdir -p {q(ext)} && tar -xzf {q(tmp)} -C {q(ext)} \\']
            b += [f'    && install -m 0755 {q(ext+"/"+a.binary_path)} {q("/usr/local/bin/"+a.command)} \\',f'    && rm -rf {q(tmp)} {q(ext)}']
    elif a.install_type=='custom':
        if not a.custom_snippet: raise HelperError('custom requires --custom-snippet')
        p=Path(a.custom_snippet)
        if not p.is_file(): raise HelperError('custom snippet file not found')
        b += [p.read_text(encoding='utf-8').rstrip()]
    else: raise HelperError('unsupported install type')
    b.append(END.format(name=a.name)); return '\n'.join(b)+'\n'

def stash_block(a):
    return f'''{BEGIN.format(name=a.name)}
RUN set -eux; \\
    install -d -m 0755 /usr/local/libexec/ai-sandbox/real; \\
    src="$(command -v {a.command})"; dest="/usr/local/libexec/ai-sandbox/real/{a.command}"; \\
    if [ -L "$src" ]; then target="$(readlink -f "$src")"; ln -s "$target" "$dest"; rm -f "$src"; else mv "$src" "$dest"; fi; \\
    test -x "$dest"
{END.format(name=a.name)}
'''

def wrapper_block(a):
    x=[BEGIN.format(name=a.name),f'  {a.command})',f'    [[ -x "$(real_tool {a.command})" ]] || fail "real {a.command} executable is missing"',f'    if is_local_only_operation "$tool" "${{1:-}}"; then exec "$(real_tool {a.command})" "$@"; fi']
    if a.mcp and a.mcp_subcommand: x += [f'    if [[ "${{1:-}}" == {q(a.mcp_subcommand)} ]]; then shift; exec /usr/local/bin/{a.name}-mcp-ssm "$@"; fi']
    if a.secret_env: x += [f'    exec "$SECRET_RUNNER" --profile {q(a.name)} -- "$(real_tool {a.command})" "$@"']
    else: x += [f'    exec "$(real_tool {a.command})" "$@"']
    x += ['    ;;',END.format(name=a.name)]; return '\n'.join(x)+'\n'

def runtime_docker_block(a):
    x=[BEGIN.format(name=a.name)]
    if a.mcp:
        x += [f'COPY .devcontainer/scripts/{a.name}-mcp-ssm.sh /usr/local/bin/{a.name}-mcp-ssm',f'RUN chmod 0755 /usr/local/bin/{a.name}-mcp-ssm \\',f'    && ln -sf /usr/local/libexec/ai-sandbox/sandbox-command-wrapper /usr/local/bin/{a.command}']
    else: x += [f'RUN ln -sf /usr/local/libexec/ai-sandbox/sandbox-command-wrapper /usr/local/bin/{a.command}']
    x += [END.format(name=a.name)]; return '\n'.join(x)+'\n'

def config_block(a):
    if not a.config_dir: return ''
    if a.config_dir.startswith('/') or '..' in Path(a.config_dir).parts: raise HelperError('--config-dir must be a safe relative path under user home')
    return f'''{BEGIN.format(name=a.name)}
RUN install -d -o "${{USER_UID}}" -g "${{USER_GID}}" -m 0750 "/home/${{USERNAME}}/{a.config_dir}"
{END.format(name=a.name)}
'''

def profile_name_block(a): return f'{BEGIN.format(name=a.name)}\n  {a.name}) ;;\n{END.format(name=a.name)}\n'
def profile_case_block(a):
    return f'''{BEGIN.format(name=a.name)}
  {a.name})
    {a.secret_env}="$(get_parameter {q(a.ssm_parameter)})"; export {a.secret_env}
    audit_safe {q(a.name)} "credential_fetch" "ssm_get_parameter" "aws-ssm" "success"
    op="$(safe_operation_from_command "$1" "${{2:-}}")"
    run_logged {q(a.name)} "$op" {q(a.name)} "https" "$@"
    ;;
{END.format(name=a.name)}
'''
def audit_block(a): return f'{BEGIN.format(name=a.name)}\n  {a.name}) ;;\n{END.format(name=a.name)}\n'
def ssm_sh_block(a): return f'''{BEGIN.format(name=a.name)}
echo; echo '--- {a.name} ---'; read -rsp '  {a.secret_env}: ' V; echo; put_s {q(a.ssm_parameter)} {q(a.name+' runtime credential')} "$V"; unset V
{END.format(name=a.name)}
'''
def ssm_ps_block(a): return f'''{BEGIN.format(name=a.name)}
Write-Host "`n--- {a.name} ---"
$SecretValue = ConvertTo-PlainText (Read-Host '  {a.secret_env}' -AsSecureString)
Set-SsmSecret -Name '{a.ssm_parameter}' -Description '{a.name} runtime credential' -Value $SecretValue
$SecretValue = $null
{END.format(name=a.name)}
'''
def squid_block(a):
    if not a.egress: return ''
    ds=[]
    for d in a.egress.split(','):
        d=d.strip()
        if d: validate_domain(d); ds.append(d)
    return BEGIN.format(name=a.name)+'\n'+'\n'.join(ds)+'\n'+END.format(name=a.name)+'\n'
def verify_block(a):
    x=[BEGIN.format(name=a.name),f"check '{a.command} is available' command -v '{a.command}'",f"check '{a.command} public command uses Admin wrapper' bash -c '[[ \"$(readlink -f /usr/local/bin/{a.command})\" == /usr/local/libexec/ai-sandbox/sandbox-command-wrapper ]]'",f"check '{a.command} real executable is stashed' test -x '/usr/local/libexec/ai-sandbox/real/{a.command}'"]
    if a.secret_env: x += [f'''check '{a.secret_env} is absent from parent environment' bash -c '! env | grep -Eq "^{a.secret_env}="' ''']
    if a.mcp: x += [f"check '{a.name} MCP wrapper is available' command -v '{a.name}-mcp-ssm'"]
    x += [END.format(name=a.name)]; return '\n'.join(x)+'\n'
def mcp_config_block(a):
    # Keep generated MCP registrations compatible with the v1.16.16 Gemini
    # security contract. Gemini strips inherited sensitive variables from stdio
    # children, so SSM-backed MCPs must carry literal AWS runtime references.
    # Non-secret MCPs do not need an env block. Never use `gemini mcp add -e`,
    # which can turn runtime values into persisted configuration.
    if a.secret_env:
        env_fragment = ''',
          env: {
            AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID",
            AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY",
            AWS_SESSION_TOKEN: "$AWS_SESSION_TOKEN"
          }'''
    else:
        env_fragment = ''
    return f'''{BEGIN.format(name=a.name)}
"$REAL_CLAUDE" mcp remove {q(a.name)} --scope user >/dev/null 2>&1 || true
"$REAL_CLAUDE" mcp add-json {q(a.name)} '{{"type":"stdio","command":"/usr/local/bin/{a.name}-mcp-ssm","args":[]}}' --scope user >/dev/null
_app_mcp_tmp="$(mktemp "${{TMPDIR:-/tmp}}/gemini-app-mcp.XXXXXX")"
jq --arg name {q(a.name)} --arg command "/usr/local/bin/{a.name}-mcp-ssm" '
  .mcpServers = ((.mcpServers // {{}}) + {{
    ($name): {{ command: $command, args: []{env_fragment}
    }}
  }})
' "$gemini_settings" > "$_app_mcp_tmp"
jq -e . "$_app_mcp_tmp" >/dev/null || {{ rm -f "$_app_mcp_tmp"; echo 'ERROR: generated Gemini MCP settings are invalid' >&2; exit 1; }}
mv "$_app_mcp_tmp" "$gemini_settings"
{END.format(name=a.name)}
'''
def mcp_wrapper(a):
    sub=f'cmd+=({q(a.mcp_subcommand)})\n' if a.mcp_subcommand else ''
    invoke=f'run-with-ssm-secrets --profile {q(a.name)} -- "${{cmd[@]}}" "$@"' if a.secret_env else '"${cmd[@]}" "$@"'
    return f'''#!/usr/bin/env bash
set -euo pipefail
set +x
umask 077
. /usr/local/libexec/ai-sandbox/mcp-wrapper-preamble
REAL=/usr/local/libexec/ai-sandbox/real/{a.command}
[[ -x "$REAL" ]] || {{ echo 'ERROR: real {a.command} executable is missing' >&2; exit 1; }}
cmd=("$REAL")
{sub}start_ms="$(date +%s%3N)"
application-audit --app mcp --event server_start --operation {q(a.name)} --target {q(a.name)} --status started --transport stdio
set +e
{invoke}
ec=$?
set -e
end_ms="$(date +%s%3N)"; status=success; (( ec == 0 )) || status=failure
application-audit --app mcp --event server_end --operation {q(a.name)} --target {q(a.name)} --status "$status" --exit-code "$ec" --duration-ms "$((end_ms-start_ms))" --transport stdio || true
exit "$ec"
'''

def plan(a):
    files=['.devcontainer/Dockerfile','.devcontainer/scripts/sandbox-command-wrapper.sh','.devcontainer/scripts/verify-runtime.sh']
    if a.secret_env: files += ['.devcontainer/scripts/run-with-ssm-secrets.sh','.devcontainer/scripts/application-audit.sh','scripts/platform/01-setup-ssm.sh','scripts/platform/01-setup-ssm.ps1']
    if a.egress: files += ['squid/whitelist.txt']
    if a.mcp: files += ['.devcontainer/scripts/configure-mcp.sh',f'.devcontainer/scripts/{a.name}-mcp-ssm.sh']
    files += [f'scripts/applications/records/{a.name}.json']
    print('=== v1.16.16 application onboarding preview ===')
    print(f'name={a.name} command={a.command} install={a.install_type} secret={a.secret_env or "none"} MCP={a.mcp}')
    print('Files to change:'); [print('  '+f) for f in files]

def add(a):
    validate_name(a.name); validate_cmd(a.command)
    if a.secret_env:
        if not re.fullmatch(r'[A-Z][A-Z0-9_]+',a.secret_env): raise HelperError('invalid --secret-env')
        if not a.ssm_parameter or not re.fullmatch(r'[a-z0-9][a-z0-9-]{1,62}',a.ssm_parameter): raise HelperError('--ssm-parameter required and must be safe')
    elif a.ssm_parameter: raise HelperError('--ssm-parameter requires --secret-env')
    if a.mcp_subcommand and not re.fullmatch(r'[A-Za-z0-9._+-]+',a.mcp_subcommand): raise HelperError('invalid --mcp-subcommand')
    record=RECORD_DIR/f'{a.name}.json'
    if record.exists(): raise HelperError(f'helper record already exists: {a.name}')
    # build all blocks first so validation happens before any write
    blocks={'install':install_block(a),'stash':stash_block(a),'config':config_block(a),'runtime':runtime_docker_block(a),'wrapper':wrapper_block(a),'verify':verify_block(a),'squid':squid_block(a)}
    if a.secret_env: blocks.update(profile_name=profile_name_block(a),profile_case=profile_case_block(a),audit=audit_block(a),ssmsh=ssm_sh_block(a),ssmps=ssm_ps_block(a))
    if a.mcp: blocks.update(mcpcfg=mcp_config_block(a),mcpwrap=mcp_wrapper(a))
    plan(a)
    if not a.apply:
        print('\nPreview only. Re-run with --apply after review.'); return
    insert_before('.devcontainer/Dockerfile','# NPM_REGISTRY supports an approved internal mirror',blocks['install'],a.name)
    insert_before('.devcontainer/Dockerfile','# ── [11] Non-root user',blocks['stash'],a.name)
    if blocks['config']: insert_before('.devcontainer/Dockerfile','# ── [12] CIS L1 hardening',blocks['config'],a.name)
    insert_before('.devcontainer/Dockerfile','# ── [17b] Admin-managed Claude Code audit hooks',blocks['runtime'],a.name)
    insert_before('.devcontainer/scripts/sandbox-command-wrapper.sh','  *) fail "unsupported sandbox command wrapper name: $tool" ;;',blocks['wrapper'],a.name)
    if a.secret_env:
        insert_before('.devcontainer/scripts/run-with-ssm-secrets.sh','  *) echo "ERROR: unknown profile: $profile" >&2; usage ;;',blocks['profile_name'],a.name)
        insert_before('.devcontainer/scripts/run-with-ssm-secrets.sh','  *) echo "ERROR: unknown profile: $profile" >&2; usage ;;\nesac',blocks['profile_case'],a.name,last=True)
        insert_before('.devcontainer/scripts/application-audit.sh','  *) echo "ERROR: unsupported audit application: $app" >&2; exit 2 ;;',blocks['audit'],a.name)
        insert_before('scripts/platform/01-setup-ssm.sh',"echo; echo '--- Registered parameters ---'",blocks['ssmsh'],a.name)
        insert_before('scripts/platform/01-setup-ssm.ps1','# [4] Verify only parameter names/types. Values are never printed.',blocks['ssmps'],a.name)
    if blocks['squid']: insert_before('squid/whitelist.txt','# ── BLOCKED (absent = blocked by default-deny)',blocks['squid'],a.name)
    insert_before('.devcontainer/scripts/verify-runtime.sh',"echo; echo '-- Configuration --'",blocks['verify'],a.name)
    if a.mcp:
        p=ROOT/f'.devcontainer/scripts/{a.name}-mcp-ssm.sh'; p.write_text(blocks['mcpwrap'],encoding='utf-8'); p.chmod(0o755)
        insert_before('.devcontainer/scripts/configure-mcp.sh','chmod -R go-rwx "$CLAUDE_CONFIG_DIR" "$gemini_config_dir" 2>/dev/null || true',blocks['mcpcfg'],a.name)
    record.write_text(json.dumps(vars(a),indent=2,default=str),encoding='utf-8')
    print('[OK] Source changes applied.')
    print(f'Next: validate-application --name {a.name} --run-lint, review diff, configure SSM, build POC, then Production acceptance.')

def remove(a):
    validate_name(a.name); record=RECORD_DIR/f'{a.name}.json'
    if not record.exists(): raise HelperError(f'no v1.16.16 helper record for {a.name}; manual removal is required (see the optional Admin application runbook if retained)')
    tag=BEGIN.format(name=a.name); files=[]
    for base in [ROOT/'.devcontainer',ROOT/'scripts/platform',ROOT/'squid']:
        for p in base.rglob('*'):
            if p.is_file():
                try:
                    if tag in p.read_text(encoding='utf-8'): files.append(p)
                except UnicodeDecodeError: pass
    print('=== removal preview ==='); print('Application:',a.name); [print('  '+str(p.relative_to(ROOT))) for p in files]
    mcp=ROOT/f'.devcontainer/scripts/{a.name}-mcp-ssm.sh'
    if mcp.exists(): print('  '+str(mcp.relative_to(ROOT)))
    if not a.apply: print('Preview only. Re-run with --apply after dependency review.'); return
    for p in files:
        if remove_marked(p,a.name)==0: raise HelperError(f'expected marker missing in {p}')
    if mcp.exists(): mcp.unlink()
    record.unlink()
    print('[OK] Helper-managed source blocks removed.')
    print('SSM parameters/vendor credentials are intentionally NOT deleted; retire old images first, then revoke/delete after dependency review.')

def validate(a):
    validate_name(a.name); record=RECORD_DIR/f'{a.name}.json'
    if not record.exists(): raise HelperError('helper record missing')
    r=json.loads(record.read_text(encoding='utf-8')); failures=[]; tag=BEGIN.format(name=a.name)
    req=['.devcontainer/Dockerfile','.devcontainer/scripts/sandbox-command-wrapper.sh','.devcontainer/scripts/verify-runtime.sh']
    if r.get('secret_env'): req += ['.devcontainer/scripts/run-with-ssm-secrets.sh','.devcontainer/scripts/application-audit.sh','scripts/platform/01-setup-ssm.sh','scripts/platform/01-setup-ssm.ps1']
    if r.get('egress'): req += ['squid/whitelist.txt']
    if r.get('mcp'): req += ['.devcontainer/scripts/configure-mcp.sh']
    print(f'=== validate helper-managed application: {a.name} ===')
    for rel in req:
        ok=tag in text(rel); print(('  [OK]   ' if ok else '  [FAIL] ')+rel); failures += [] if ok else [rel]
    if r.get('mcp'):
        p=ROOT/f'.devcontainer/scripts/{a.name}-mcp-ssm.sh'; ok=p.exists(); print(('  [OK]   ' if ok else '  [FAIL] ')+'MCP wrapper'); failures += [] if ok else ['MCP wrapper']
    for p in ROOT.rglob('*'):
        if not p.is_file(): continue
        try:s=p.read_text(encoding='utf-8')
        except UnicodeDecodeError: continue
        if s.count(tag)!=s.count(END.format(name=a.name)): failures.append('unbalanced markers:'+str(p.relative_to(ROOT)))
    if a.run_lint:
        rc=subprocess.run([str(ROOT/'scripts/ci/lint-package.sh')],cwd=ROOT).returncode
        if rc: failures.append('package lint')
    if failures: raise HelperError('validation failed: '+', '.join(failures))
    print('VALIDATION PASSED.')

def parser():
    p=argparse.ArgumentParser(); sp=p.add_subparsers(dest='action',required=True)
    a=sp.add_parser('add'); a.add_argument('--name',required=True); a.add_argument('--command',required=True); a.add_argument('--install-type',required=True,choices=['npm','uv','apt','archive','custom']); a.add_argument('--package'); a.add_argument('--version'); a.add_argument('--url'); a.add_argument('--sha256'); a.add_argument('--archive-format',choices=['binary','zip','tar.gz']); a.add_argument('--binary-path'); a.add_argument('--custom-snippet'); a.add_argument('--secret-env'); a.add_argument('--ssm-parameter'); a.add_argument('--egress'); a.add_argument('--config-dir'); a.add_argument('--mcp',action='store_true'); a.add_argument('--mcp-subcommand'); a.add_argument('--apply',action='store_true')
    r=sp.add_parser('remove'); r.add_argument('--name',required=True); r.add_argument('--apply',action='store_true')
    v=sp.add_parser('validate'); v.add_argument('--name',required=True); v.add_argument('--run-lint',action='store_true')
    return p

def main():
    a=parser().parse_args()
    try:
        {'add':add,'remove':remove,'validate':validate}[a.action](a)
    except HelperError as e:
        print('ERROR:',e,file=sys.stderr); return 2
    return 0
if __name__=='__main__': raise SystemExit(main())
